version: '3'
services:
  estimake-server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - estimake-network
    restart: unless-stopped
  estimake-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - estimake-network
    restart: unless-stopped
networks:
  estimake-network:
 